# name of disease/trait. used as prefix for output files.
study: skin_disease

# File downloaded from GWAS catalog
gwas_catalog: assets/gwas_catalog_v1.0-associations_e100_r2021-04-20.tsv
gwas_trait_key: "DISEASE/TRAIT"

# Disease column with (optionally simplified) disease terms
# GWAS_term column with terms that must exactly match DISEASE/TRAIT column in catalog
disease_list: skin_disease_list.tsv

# manually include snps not in catalog
extra_gwas: skin_disease_SNPS_other_papers.txt

# Only include GWAS SNPs with p-value below this threshold
gwas_pvalue_threshold: 5e-8

r2_threshold: 0.8
r2_threshold_pop_spec: 0.8

# Key to associate gwas samples with 1KGP populations
# Comment out to not match and only use populations listed below
gwas_pop_key: assets/gwas_populations_keys.txt
max_pops: 5

# Populations to run regardless of gwas sample
pops:
  - ALL
  # - AFR
  # - AMR
  # - EAS
  # - EUR
  # - SAS

# LDLink queries are  cached.
# When the pipeline is re-run, do you want to retry SNPs that produced an error?
# This will cause the pipeline to re-run slower. 
retry_errors: false

# comment out to not use
gtex_table: ~/data/GTEx/GTEx_Analysis_2017-06-05_v8_WholeGenomeSeq_838Indiv_Analysis_Freeze.lookup_table.txt.gz

# random number seed
seed: 1234

# Specify genomic regions to label and filter SNPs either in csv format
epigenome_csv: epigenome.csv
# or YAML format below
# epigenome:
#   - ATAC:
#       bedfile: data/ggr.atac.idr.master.bed.gz
#       genome: hg19
#       filter: true
#   - H3K27ac:
#       bedfile: data/ggr.histone.H3K27ac.overlap.master.bed.gz
#       genome: hg19
#       filter: true
#   - H3K27me3:
#       bedfile: data/ggr.histone.H3K27me3.overlap.master.bed.gz
#       genome: hg19
#       filter: false
#   - H3K4me1:
#       bedfile: data/ggr.histone.H3K4me1.overlap.master.bed.gz
#       genome: hg19
#       filter: true


# uncomment to filter out variants falling in gene annotations
txdb_filters:
  - coding
#  - spliceSite
#  - fiveUTR
#  - threeUTR
#  - intron
#  - promoter
#  - intergenic


# this will label eQTLs, but filtering not yet implemented
eqtls:
  - skin_not_sun_exposed:
      file: data/Skin_Not_Sun_Exposed_Suprapubic.v8.signif_variant_gene_pairs.txt.gz
      filter: false
  - skin_sun_exposed:
      file: data/Skin_Sun_Exposed_Lower_leg.v8.signif_variant_gene_pairs.txt.gz
      filter: false

revcomp: True # Reverse complement all of the fragments, doubling the library size

sub_libraries: 1

barcodes: assets/barcodes16-1.txt
bc_per_frag: 10 # Set to 0 for no barcodes. No internal cloning site will be included. For soft-barcoded libraries.

# how many scramble control pairs
random_controls: 250
random_controls_with_mutation: 250

# Options for building the oligos
oligo:
  max_len: 230
  primer_5p: ACTGGCCGCTTCACTG
  primer_3p: AGATCGGAAGAGCGTCG
  bc_len: 16
  max_indel: 3 # will not include indel variants with more than this number of bp

# List all enzymes used in cloning.
# These sites will be randomly mutated if they exist in the genomic sequence
# comment out the list if not using restriction enzymes to clone
restriction_enzymes:
  EcoRI: GAATTC
  BamHI: GGATCC
  XhoI: CTCGAG
  NheI: GCTAGC

cloning_site:
  enzyme1: XhoI
  enzyme2: NheI
  stuffer_bp: 10 # length of stuffer between sites
  stuffer_GC: 0.5 # GC content of stuffer

